// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
  

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC08FNGkR5pmgsKVpzU2OQ16-YneTXYCnM',
    appId: '1:611758054862:web:9a15ff6f0dc41bab64df9f',
    messagingSenderId: '611758054862',
    projectId: 'labuena-9ec06',
    authDomain: 'labuena-9ec06.firebaseapp.com',
    storageBucket: 'labuena-9ec06.firebasestorage.app',
    measurementId: 'G-SEJBHXGDEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxtLzw3VCoBMbH_0EW9nwu1CJVus7MFyk',
    appId: '1:611758054862:android:128972949d45026d64df9f',
    messagingSenderId: '611758054862',
    projectId: 'labuena-9ec06',
    storageBucket: 'labuena-9ec06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKnnCz4Du06iFhhIScdY4ClDnyH0wgdJU',
    appId: '1:611758054862:ios:14640e492c87f6ea64df9f',
    messagingSenderId: '611758054862',
    projectId: 'labuena-9ec06',
    storageBucket: 'labuena-9ec06.firebasestorage.app',
    iosBundleId: 'com.example.conia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKnnCz4Du06iFhhIScdY4ClDnyH0wgdJU',
    appId: '1:611758054862:ios:14640e492c87f6ea64df9f',
    messagingSenderId: '611758054862',
    projectId: 'labuena-9ec06',
    storageBucket: 'labuena-9ec06.firebasestorage.app',
    iosBundleId: 'com.example.conia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC08FNGkR5pmgsKVpzU2OQ16-YneTXYCnM',
    appId: '1:611758054862:web:14aa2ac970c4794464df9f',
    messagingSenderId: '611758054862',
    projectId: 'labuena-9ec06',
    authDomain: 'labuena-9ec06.firebaseapp.com',
    storageBucket: 'labuena-9ec06.firebasestorage.app',
    measurementId: 'G-07Q77LHW8Z',
  );
}
